content_type_breadcrumb:
  type_article: 'main:menu_link_content:a92b4794-19e1-465f-847c-5f1d9620ba37'
  type_landing_page: ''
  type_page: ''
  type_webform: 'main:menu_link_content:768e83dd-c284-4069-b67c-cd2d23dcf832'
  view_pd_core_ati_details: null
  view_pd_core_contracts_details: null
  view_pd_core_grants_details: null
  view_pd_core_hospitalityq_details: null
  view_pd_core_inventory_details: null
  view_pd_core_reclassification_details: null
  view_pd_core_travela_details: null
  view_pd_core_travelq_details: null
  view_pd_core_wrongdoing_details: null
  vocabulary_blog_author: 'main:menu_link_content:a92b4794-19e1-465f-847c-5f1d9620ba37'
  vocabulary_category: 'main:menu_link_content:a92b4794-19e1-465f-847c-5f1d9620ba37'
