third_party_settings: {  }
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: libraries/theme-gcweb/assets/sig-blk-en.svg
favicon:
  use_default: false
  path: 'public://favicon.ico'
  mimetype: image/vnd.microsoft.icon
